# Os valores abaixo estão codificados em base64.
# Para gerar novos valores:  echo -n 'valor' | base64
#
# Valores atuais:
#   POSTGRES_USER     = postgres       → cG9zdGdyZXM=
#   POSTGRES_PASSWORD = 20241si036     → MjAyNDFzaTAzNg==
#   POSTGRES_DB       = catalogo_db    → Y2F0YWxvZ29fZGI=
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: catalogo
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MjAyNDFzaTAzNg==
  POSTGRES_DB: Y2F0YWxvZ29fZGI=
