apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: catalogo
  labels:
    app: fastapi
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
